loadConfFromKeyVault: true

azure:
  tenantId: <tenantId>

  keyVault:
    uri: <your keyvault url>

  auth:
    servicesApp:
      appId: <your appid>
      secret: <your appSecret>

externalServiceUrl: https://<your dns hostname>

deployment:
  microServices:
    engineeringTool:
      enabled: true
    telemetryCdmProcessor:
      enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-<your alias>
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/session-cookie-name: affinity
      nginx.ingress.kubernetes.io/session-cookie-expires: "14400"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "14400"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
    - hosts:
      - <your dns hostname>
      secretName: tls-secret
    hostName: <your dns hostname>